### ISSUE TITLE
E: Failed to fetch ... Could not connect to

### ISSUE THREAD

**Issue by Mezzano** [rickysarraf/apt-offline#136]
I am busy with the process to dist-upgrade several unconnected devices.

I have created a .sig file from the "A" device that is an ubuntu 16.04 base from http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04.6-base-arm64.tar.gz plus several specific packages installed on it.
The "B", "C" and all the other devices might have some additionnal packages installed on them (that are thus not part of the .sig database from the "A" device).

When I run the following commands on them, the dist-upgrade is not executed because it finds some unknown packages that it can't upgrade.

apt-offline install $BIONIC_DIR
apt -y dist-upgrade -o Dpkg::Options::="--force-confold"

How could I tell apt just to not try to upgrade those unknown packages and proceed with the dist-upgrade?

**Comment by rickysarraf** [comment]
Please share full console logs of the commands you run and their output. Rigth from the beginning, i.e. from the `apt-offline set ...` command.

**Comment by Mezzano** [comment]
# offline machine ubuntu 16.04
sudo apt-offline set ubuntu1604.sig --update --upgrade --upgrade-type dist-upgrade
 
# online machine ubuntu 16.04
sudo apt-offline get ubuntu1604.sig --bundle ubuntu-18.04.tar.gz
 
# offline machine ubuntu 16.04
sudo apt-offline install ubuntu-18.04.tar.gz
apt -y dist-upgrade -o Dpkg::Options::="--force-confold"

Meanwhile, on the offline machine, a package was installed (by example 'watchdog') that is not included in the .sig and thus in the single tarball. When dist-upgrade occurs, it fails to fetch the upgrade of watchdog. How can I prevent apt to upgrade it or to just proceed?

I don't have the logs anymore, if you really need them, I will redo the procedure to get them.

**Comment by rickysarraf** [comment]
> I don't have the logs anymore, if you really need them, I will redo the procedure to get them.

Please do. The information you've shared so far is not useful to ascertain what may have gone wrong in your workflow.

**Comment by rickysarraf** [comment]
> Offline machine ubuntu 16.04
> sudo apt-offline set ubuntu1604.sig --update --upgrade --upgrade-type dist-upgrade
> 

Also you shouldn't use the `--update` and `--upgrade` options together in unison. Because by using them together, you are creating a cyclic loop of updating the apt database.

Run `--update` separately, followed by `--upgrade`. Then you'll not have new downloads required (like in your case, the `watchdog`)

For more details, please see the HOWTO.
https://github.com/rickysarraf/apt-offline/wiki/HOWTO

**Comment by rickysarraf** [comment]
Note to self: Our defaults for the `set` command is to invoke `--update` and `--upgrade` together. This has the potential to have undesired effects, especially on development releases like `Debian Testing and Debian Unstable`.

We should drop the defaults of the above and make the user pass the options explicitly. We should also update the documentation to reflect the same. Some simple english should be added to explain the purpose of the options, and why, for majority of the normal users, we should be using one at a time.

Also, on the GUI side, neither of the option is enabled by default and the user is expected to check the right options first.
![image](https://user-images.githubusercontent.com/65480/98642331-4d3c7e80-2353-11eb-89f0-32ac4b9b97df.png)

**Comment by Mezzano** [comment]
Hello,

After reviewing my post and your blog, I wonder if apt-offline can really be used for complete offline distribution upgrade.
I see that it is often used for installing "some" packages on offline devices but is it really able to offline dist-upgrade?

I have found this post where someone uses apt-offline for this purpose:
https://unix.stackexchange.com/questions/181651/debian-offline-dist-upgrade-in-one-step

My issue is that I need to apply this procedure on hosts who might have installed packages not present on the host on which I created the .sig file.

The problem arise when the apt command tries to upgrade packages that were not on the host used for .sig file creation.
My problem seems more related to the apt command that should ignore those packages instead of trying to fetch them but I don't know how to modify apt behaviour.

I have redone the procedure and used the following command to create the signature:

sudo ./apt-offline set ubuntu.sig --upgrade-type dist-upgrade

The complete logs can be found here:
https://gist.github.com/Mezzano/a5bd9eabb0f7e9688817717262041fa0

The only solution I have I mind is to parse "apt dist-upgrade" output and "apt remove" the packages it tries to fetch and rerun the "apt dist-upgrade" command. Please, let me know if you have a better idea.

Thanks a lot

**Comment by rickysarraf** [comment]
Do it one at a time. First run `apt-offline set /tmp/updates.uris --update`. Then apply that data on the offline machine. Then on the offline machine, run `apt-offline set /tmp/upgrade.uris --upgrade --upgrade-type dist-upgrade`. Then apply that data on the offline machine after you have fetched it.

So it is a round-trip. If you just run `apt-offline set /tmp/set.urir`, it implies `--update` as well as `--upgrade`, which makes it a loop.


In your logs, you can see that apt-offline did get the major chunk of data. But since you hadn't explicitly set the options, it took both. Which is why when you did `apt-offline install ...`, it again refreshed the apt package indices; resulting in more upgradable packages.

Just use one option at a time and follow the workflow I explained. It will work for your scenario (`dist-upgrade`)

**Comment by Mezzano** [comment]
Hi,
Just to let you know, that I did run apt-offline with one option at a time.
But as expected, on some different host, where there was some totally unknown installed packaged, it couldn't upgrade.
I have thus created a solution that parses apt errors output, uninstalls those unupgradable packages and it finally succeeds to dist-upgrade.
You can close this issue.
Thanks for your help.
