### ISSUE TITLE
Straightforward way to install APT-Offline on offline Ubuntu 16.04

### ISSUE THREAD

**Issue by Yoann85** [rickysarraf/apt-offline#210]
Hi,  I'm trying to install APT-Offline to a Ubuntu 16.04 which isn't connected to the internet.  I've downloaded the APT-offline repo and copied it to the Ubuntu server.   Running 'sudo apt install apt-offline ' generates an error "the following packages have unmet dependencies".  I've found, and install most dependencies but I'm not able to find 'python-argparse'.  Suggestions?

_Originally posted by @pjohnson-1 in https://github.com/rickysarraf/apt-offline/issues/88#issuecomment-1184793954_
            
Hi, I have trouble to install apt-offline on an offline ubuntu 16.04 machine, as mentioned by @pjohnson-1 (my apologize if the user opened an issue, I didn't find it).
I tried to get all needed packages using  apt-rdepends. It took extra steps to fix errors getting debconf, pinentry and python-argparse packages. Then, when using dpkg on the offline machine, it fails because of python packages are missing. And it's quite a mess to install them, I can't find out the order of dependencies.

Until now I only managed to use apt-offline by cloning the repo on the offline machine.
**--> Is there a straightforward way to install it on the offline machine ?** All documentation I found assumes that apt-offline is already installed, which is not my case...

Thank you

**Comment by rickysarraf** [comment]
It all depends on the stock version of Python and other libraries shipped with Ubuntu 16.04. If you install the version of `apt-offline` that Ubuntu stock is shipping, you may not have issues.

Problems arise when you try to install newer `apt-offline` with newer dependencies on an older distribution like Ubuntu 16.04.

Note that I've kept the `apt-offline` dependencies to bare minimum to ensure it can operate under multiple environments.


The `cloning` approach may work better because there all dependencies are embedded in the code/repository itself.
