### ISSUE TITLE
streamlining the process with defaults

### ISSUE THREAD

**Issue by eighthave** [rickysarraf/apt-offline#46]
Thanks again for apt-offline, it is a wonderful tool and makes it actually possible to run a machine offline! There are a couple of little details that would make it a lot easier, mostly it is a matter of setting default values for the signature file and the downloaded files, be it either the bundle or the individual files.  Ultimately, I'd like to be able to use apt-offline like this:

```
apt-offline set
apt-offline get
apt-offline install
```

That means there would need to be defaults for the signature file location, the action (.e.g `--update`, and/or `--upgrade`, and the downloaded file location.  There are a bunch of different ways this could be achieved, so I'm opening this issue to figure that out.  Then I'd be happy to implement it and submit a pull request.

There could be _/etc/apt-offline.conf_ where the defaults are set.  On Debian, it could use a default mount location like _/media/usb_ and build default paths off of that. In that case, it would make sense to have a `--basepath` option to override just the _/media/usb_ part.  Or other ways like using the current directory as the path, then use default filenames for the signature file and the downloads.

**Comment by rickysarraf** [comment]
Hello Hans,

Thank you for your bug report.


On Tue, 2016-01-26 at 07:18 -0800, Hans-Christoph Steiner wrote:
> Thanks again for apt-offline, it is a wonderful tool and makes it
> actually possible to run a machine offline! There are a couple of
> little details that would make it a lot easier, mostly it is a matter
> of setting default values for the signature file and the downloaded
> files, be it either the bundle or the individual files. Ultimately,
> I'd like to be able to use apt-offline like this:
> apt-offline set
> apt-offline get
> apt-offline install
> That means there would need to be defaults for the signature file
> location, the action (.e.g --update, and/or --upgrade, and the
> downloaded file location. There are a bunch of different ways this
> could be achieved, so I'm opening this issue to figure that out. Then
> I'd be happy to implement it and submit a pull request.

Thank you.

Of the 3, the action part is already done. So just calling set will
result in --update and --upgrade being triggered together.

rrs@learner:/tmp$ sudo apt-offline set foo.sig
[sudo] password for rrs: 

Generating database of files that are needed for an update.

Generating database of file that are needed for operation upgrade
2016-02-05 / 15:18:26 ♒♒♒  ☺    

But the help documentation doesn't give that hint. Perhaps something
python argparse should do.



For downloads, if the download path isn't specified, apt-offline will
look for tmpdir on all platforms. On Linux, today, it'd result in /tmp,
which is wrong now, because all new standard Linux installs now have
/tmp as ramfs. Ideally, python should now return /var/tmp/ as a tpmdir,
but I don't think that part has support from all parties.

So one reason why some options were marked explicit was to force the
user to define them.

> There could be /etc/apt-offline.conf where the defaults are set. On
> Debian, it could use a default mount location like /media/usb and
> build default paths off of that. In that case, it would make sense to
> have a --basepath option to override just the /media/usb part. Or
> other ways like using the current directory as the path, then use
> default filenames for the signature file and the downloads.

This sounds better. Is there any standard practise about paths ? On my
box, all user plugged devices result in getting automounted under
/media/rrs/


-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by eighthave** [comment]
I can't see how copying to /tmp helps the user.  Isn't apt-offline built around using a removable drive to move the data?  If so, I think it would make more sense to quit with an error than put files into /tmp, or any dir on the offline device.  The error would be something like "provide the path to removable storage".

`/etc/apt-offline.conf` and `--basepath` are the easiest things to implement.  Using something like dbus, it should be possible to detect whether a USB disk is attached:
https://linuxmeerkat.wordpress.com/2014/11/12/python-detection-of-usb-storage-device/

**Comment by rickysarraf** [comment]
On Fri, 2016-02-05 at 02:39 -0800, Hans-Christoph Steiner wrote:
> I can't see how copying to /tmp helps the user. Isn't apt-offline
> built around using a removable drive to move the data? If so, I think
> it would make more sense to quit with an error than put files into
> /tmp, or any dir on the offline device. The error would be something
> like "provide the path to removable storage".


Yes. And I think that's what we are doing right now. Only when no path
is provided, we do the download in tpmdir. I think downloads are put in
tmpdir otherwise too. Python's tempfile put an fd in tmpdir. If that
has to change, the Linux distribution vendors have to agree and promote
/var/tmp as tmpdir.

> /etc/apt-offline.conf and --basepath are the easiest things to
> implement. Using something like dbus, it should be possible to detect
> whether a USB disk is attached:
> https://linuxmeerkat.wordpress.com/2014/11/12/python-detection-of-usb
> -storage-device/

Yes. This sounds good. Please provide patch if you already have. I
wouldn't bother much about dbus (or otherwise would put it under
try/except) because apt-offline would also be running on non-Linux
platforms (For the download part).


-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by eighthave** [comment]
I'll reiterate to hopefully clarify my point: I think automatically
putting stuff on the local machine (anywhere, /tmp or otherwise) is
actually making apt-offline harder to use.  It makes it seem like it is
doing the full requested action, when really it is not.  I was initially
quite confused by this behavior.

If apt-offline is not configured to put the signature or downloaded
files somewhere specific, then apt-offline should tell the user to
specify a path in an error message, then quit without doing anything.

I'm happy to implement this error message, as well as
/etc/apt-offline.conf and --basepath if you agree to the approach.

**Comment by rickysarraf** [comment]
On Fri, 2016-02-05 at 14:01 -0800, Hans-Christoph Steiner wrote:
> 
> I'll reiterate to hopefully clarify my point: I think automatically
> putting stuff on the local machine (anywhere, /tmp or otherwise) is
> actually making apt-offline harder to use. It makes it seem like it
> is
> doing the full requested action, when really it is not. I was
> initially
> quite confused by this behavior.
> 

I don't think it is as big a concern as you are raising.

For certain tasks, the options/args are mandatory. For some, where it
is not mandatory, it does report where it saved the file.

Take the following as example. Here, I'm not specifying the target save
location.

rrs@learner:/var/tmp$ apt-offline get /tmp/debian-template-upgrade.uris 
--threads 5  --cache-dir /var/cache/apt/archives/

Fetching APT Data

WARNING: If you are on a slow connection, it is good to
WARNING: limit the number of threads to a low number like 2.
WARNING: Else higher number of threads executed could cause
WARNING: network congestion and timeouts.

dash copied from local cache directory
/var/cache/apt/archives/.                              
debianutils copied from local cache directory
/var/cache/apt/archives/.                              
bsdutils copied from local cache directory
/var/cache/apt/archives/.                              
findutils copied from local cache directory
/var/cache/apt/archives/.                              

....snipped....
                          
libusb-1.0-0 copied from local cache directory
/var/cache/apt/archives/.                              
irqbalance copied from local cache directory
/var/cache/apt/archives/.                              
os-prober copied from local cache directory
/var/cache/apt/archives/.                              
publicsuffix copied from local cache directory
/var/cache/apt/archives/.                              
174 / 174 items: [##############################] 100.0% of 105 MiB
Downloaded data to /tmp/apt-offline-downloads-10488
2016-02-08 / 17:04:03 ♒♒♒  ☺ 


It is just that the location, if not provided, is built up from tmpdir.


> If apt-offline is not configured to put the signature or downloaded
> files somewhere specific, then apt-offline should tell the user to
> specify a path in an error message, then quit without doing anything.
> 

Please note, that above, it does report its location, where it saved
the data.


> I'm happy to implement this error message, as well as
> /etc/apt-offline.conf and --basepath if you agree to the approach.

If we really want to, then just switching some of the non-mandatory
options to mandatory, will suffice the requirement. You can add the
defaults right in the argument parser.

Then the 2 together should be good, so that if the .conf file is non-
existent, it should still take sensible defaults.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by eighthave** [comment]
Is there ever a use case that needs the downloaded files to be in /tmp?
 My guess is no, I cannot think of anything.  In that case, this default
behavior is doing something that will never be directly helpful to the
user.  Therefore, apt-offline should give an error message to inform the
user how to do what they are trying to do.

**Comment by rickysarraf** [comment]
On Mon, 2016-02-08 at 04:34 -0800, Hans-Christoph Steiner wrote:
> 
> Is there ever a use case that needs the downloaded files to be in
> /tmp?
> My guess is no, I cannot think of anything. In that case, this
> default
> behavior is doing something that will never be directly helpful to
> the
> user. Therefore, apt-offline should give an error message to inform
> the
> user how to do what they are trying to do.
> 

I have to agree with you.

I just made the change and have pushed it to the repo.

Fixed in commit id: f6ebbec6e36b2d27ded60100d1bd17e77d6ba1d5

rrs@learner:~/.rrs-home/devel/apt-offline/apt-offline (master)$ ./apt-
offline get /tmp/set.uris --threads 5 --cache-dir
/var/cache/apt/archives/

Fetching APT Data

ERROR: Please provide a target download file/folder location.
2016-02-08 / 18:38:14 ♒♒♒    ☹  => 1  


rrs@learner:~/.rrs-home/devel/apt-offline/apt-offline (master)$ ./apt-
offline get /tmp/set.uris --threads 5 --cache-dir
/var/cache/apt/archives/ -d /var/tmp/apt-offline-dafdas

Fetching APT Data

WARNING: If you are on a slow connection, it is good to
WARNING: limit the number of threads to a low number like 2.
WARNING: Else higher number of threads executed could cause
WARNING: network congestion and timeouts.

 58 /  58 items: [##############################] 100.0% of 24
MiBes/                                           
Downloaded data to /var/tmp/apt-offline-dafdas
2016-02-08 / 18:39:02 ♒♒♒  ☺    



rrs@learner:~/.rrs-home/devel/apt-offline/apt-offline (master)$ ./apt-
offline get /tmp/set.uris --threads 5 --cache-dir
/var/cache/apt/archives/ --bundle /var/tmp/apt-offline-dadfads.zip

Fetching APT Data

WARNING: If you are on a slow connection, it is good to
WARNING: limit the number of threads to a low number like 2.
WARNING: Else higher number of threads executed could cause
WARNING: network congestion and timeouts.

 58 /  58 items: [##############################] 100.0% of 24
MiBs/                                            
Downloaded data to /var/tmp/apt-offline-dadfads.zip
2016-02-08 / 18:39:50 ♒♒♒  ☺    



-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by eighthave** [comment]
awesome, thanks!  Any chance of v1.8 being uploaded to Debian before Feb 17th so that it is automatically included in the next Ubuntu LTS release?
https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule

**Comment by rickysarraf** [comment]
On Tue, 2016-02-09 at 09:44 -0800, Hans-Christoph Steiner wrote:
> awesome, thanks! Any chance of v1.8 being uploaded to Debian before
> Feb 17th so that it is automatically included in the next Ubuntu LTS
> release?
> https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule

I'll see if that is doable. But I still have some tests that it has to
run through.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by eighthave** [comment]
just had a thought: I think it could make sense to have the default locations be:
* apt-offline set: `os.path.join(os.getcwd(), 'apt-offline.sig')`
* apt-offline get: `os.path.join(os.getcwd(), 'apt-offline.sig')` and `os.path.join(os.getcwd(), 'apt-offline-download')`
* apt-offline install: `os.path.join(os.getcwd(), 'apt-offline.sig')`

Then without any args, apt-offline would use the current directory.

**Comment by rickysarraf** [comment]
This bug report should have been long closed, based on f6ebbec6e36b2d27ded60100d1bd17e77d6ba1d5

Regarding --basepath, I'd rather prefer those options/args to be explicitly specified.
