### ISSUE TITLE
status file when creating sig

### ISSUE THREAD

**Issue by maxiecool2** [rickysarraf/apt-offline#75]
feature request
include the status file when creating sig
to be able to upgrade once updated

group multiple sigs at once
ie. if they use the same lists just download the list once

**Comment by rickysarraf** [comment]
I am not sure what you mean by `status` file. You get the offline machine's package manager's status only after you've applied the apt-offline data. Without it, you cannot generate any new status.

**Comment by maxiecool2** [comment]
1. create sig file status data included on offline machine
 2. update lists for offline machine on connected system
 3. download packages using status data
4. install packages on offline machine
 job done no running backwards and forwards
 
 easier than using apt-get -c=x.conf
the file /etc/apt/status contains a list of installed packages
incorporate the status file in the .sig
 i hope this helps
 mat
  

----------------------------------------

**Comment by rickysarraf** [comment]
There's nothing like `/etc/apt/status` in standard apt code base. Where do you get that from ?

**Comment by maxiecool2** [comment]
i currently use apt with individual config files within the config files is the location for the status file
 after each upgrade i copy over the upgraded status file in prepared for next upgrade
  
 sample apt.config file for offline system
 Dir "/";
Dir::State "/home/max/apt/package.list/";
Dir::State::lists "/home/max/apt/package.list/linuxbox/";
Dir::State::status "/home/max/apt/linuxbox/status";
Dir::Cache: "/home/max/apt/linuxbox";
Dir::Cache::archives "/home/max/apt/linuxbox/deb/";
Dir::Etc: "/home/max/apt/linuxbox/";
Dir::Etc::main "/home/max/apt/linuxbox.apt.config";
Dir::Etc::parts "/home/max/apt/linuxbox/apt.conf.d/";
Dir::Etc::PrefrencesParts "/home/max/apt/linuxbox/prefrences.d/";
Dir::Etc::sourcelist "/home/max/apt/linuxbox/sources.list";
Dir::Etc::sourceparts "/home/max/apt/linuxbox/sources.list.d/";
Dir::Etc::Trusted "/home/max/apt/linuxbox/trusted.gpg";
Dir::Etc::TrustedParts "/home/max/apt/linuxbox/trusted.gpg.d/";
Acquire::Queue-Mode "Access";
APT::Get::Download-Only "true";
APT::Get::AllowUnauthenticated;
APT::Default-Release "trusty-updates";
APT::Architecture "i386";
Dpkg::Progress;
  
  
 the default location for a config file is /etc/apt but normally a config is created internally and no file given
 mat

----------------------------------------

**Comment by rickysarraf** [comment]
Okay. Now I get it. But that is anyways beyond the scope of apt-offline.

apt-offline tries to only bridge the gap of the missing network. For most of the other tasks, it relies on apt. It does not try to do the same thing that apt already does.

I'm still not sure what purpose the `status` file is serving you. Because when apt-offline generates the signature, it does not need anything else. And once apt-offline downloads the payload, based on the signature file, it can only make sense of new payload (the .debs to download) after it has synced the update data to the offline machine. Trying to ascertain the list of upgradable packages from the status file would never work correct because apart from version changes, there are other factors that the package manager accounts for.

**Comment by maxiecool2** [comment]
the status file acts as the list of currently installed packages with in normal apt, which is what its meant to do, but from the offline system
 how difficult would it be to implement it within apt-offline sig file? so apt-offline can then begin upgrading its packages once it has finished updating its lists
 mat
  
  
  

----------------------------------------

**Comment by rickysarraf** [comment]
I don't have any plans to implement this feature. I intend to keep `apt-offline` simple in terms of delegating tasks that are better handled in the base `apt` tool.
