### ISSUE TITLE
unknown url type: ssh

### ISSUE THREAD

**Issue by ralequi** [rickysarraf/apt-offline#94]
Hi,

I have a custom repository in a format like this:
`deb ssh://xxx@yyy:/usr/local/debrepo bionic stable`

In some cases, I would like to update my systems in a "offline" mode. However, I'm getting an error:
```
Downloading ssh://xxx@yyy:/usr/local/debrepo/dists/bionic/Release.gpg                                                             
WARN: ssh://xxx@yyy:/usr/local/debrepo/dists/bionic/Release.gpg - 504 - unknown url type: ssh   
```

I think the problem is that the "ssh" method is not implemented.
I don't know how complex it is or how much time do you have to implement the changes.

If you feel that you don't have much time (or there is an easy fix/alternative in my config that do not involves change ssh into https repo, unless certificate-based auth is allowed) I can try to find a way to implement it. If that is the case, function/file to start with would be much appreciated.

Thank you very much

**Comment by rickysarraf** [comment]
If you have a local mirror of multiple packages, you can sshfs mount it. And then, you can use apt-offline's `--cache-dir` option, which cycles through the cache to look for the available data. But this only applies for .deb packages.

For update database metadata, we don't do too many stuff. The reason being because the `get` operation is expected to run on multiple platforms and having apt's features on all those platforms may not be possible. Features like `Package Diffs`, `Bug Reports` etc.

But if you have spare time and can submit a patch, I wouldn't mind considering it. But preferred option would be if that could work on all platforms.

**Comment by rickysarraf** [comment]
With commit https://github.com/rickysarraf/apt-offline/commit/50267a68844b70cff4c8d422df7d760a2595a65b we now check for the URL type (http/ftp) and ignore all other types.

For this particular case, as I mentioned before, leveraging a mirror is accomplished through `--cache-dir` option. This will only work for `.debs` though.
